If you have the bug, then generating the example with test.py and running it will take super-long time (with m=50 it won't terminate actually). 
